// // /*import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // import ClientProviders from "./ClientProvider";
// // import { CartProvider } from "@/contexts/CartContext";
// // import { WishlistProvider } from "@/contexts/WishlistContext";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="en">
// //       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
// //         <ClientProviders>
// //           <CartProvider>
// //             <WishlistProvider>
// //               {children}
// //             </WishlistProvider>
// //           </CartProvider>
// //         </ClientProviders>
// //       </body>
// //     </html>
// //   );
// // }*/

// // import type { Metadata } from "next";
// // import { Inconsolata } from "next/font/google";
// // import "./globals.css";

// // import ClientProviders from "./ClientProvider";
// // import { CartProvider } from "@/contexts/CartContext";
// // import { WishlistProvider } from "@/contexts/WishlistContext";

// // import { Toaster } from 'react-hot-toast';
// // import Footer from "@/components/New/components/Footer";
// // import Navigation from "./SHD-COMPONENTS/components/Navigation";

// // // Load Inconsolata font
// // const inconsolata = Inconsolata({
// //   subsets: ["latin"],
// //   display: "swap",
// //   variable: "--font-inconsolata",
// // });

// // export const metadata: Metadata = {
// //   title: "Shaddyna",
// //   description: "For great ideas and great products",
// // };

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${inconsolata.variable} font-inconsolata bg-background text-foreground antialiased`}
// //       >
// //         <ClientProviders>
// //           <CartProvider>
// //             <WishlistProvider>
// //             <div className='flex min-h-screen flex-col'>  
// //                <Navigation />
// //                 <main className="flex-1"> 
// //               {children}
// //                <Toaster position="top-center" />
// //               <Footer />
// //               </main>
// //              </div>  
// //             </WishlistProvider>
// //           </CartProvider>
// //         </ClientProviders>
// //       </body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import { Inconsolata } from "next/font/google";
// import "./globals.css";

// import { AuthProvider } from "@/shd-contexts/AuthContext";
// import Navigation from "./SHD-COMPONENTS/components/Navigation";

// // Load Inconsolata font
// const inconsolata = Inconsolata({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-inconsolata",
// });

// export const metadata: Metadata = {
//   title: "Shaddyna",
//   description: "For great ideas and great products",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${inconsolata.variable} font-inconsolata bg-background text-foreground antialiased`}
//       >
//         <AuthProvider>
//           <div className="flex min-h-screen flex-col">
//             <Navigation />
//             <main className="flex-1">
//               {children}
//             </main>
//           </div>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Comfortaa } from "next/font/google";
// import "./globals.css";

// import { AuthProvider } from "@/shd-contexts/AuthContext";
// import Navigation from "./SHD-COMPONENTS/components/Navigation";

// const comfortaa = Comfortaa({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-comfortaa",
//   weight: ["300", "400", "500", "600", "700"],
// });

// export const metadata: Metadata = {
//   title: "Shaddyna",
//   description: "For great ideas and great products",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${comfortaa.variable} font-comfortaa bg-background text-text antialiased`}
//       >
//         <AuthProvider>
//           <div className="flex min-h-screen flex-col">
//             <Navigation />

//             <main className="flex-1">
//               {children}
//             </main>
//           </div>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/shd-contexts/AuthContext";
import Navigation from "./SHD-COMPONENTS/components/Navigation";
import { headers } from "next/headers";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-comfortaa",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Shaddyna",
  description: "For great ideas and great products",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";

  const isSocialsPage =
    pathname === "/socials" || pathname.startsWith("/socials/");

  return (
    <html lang="en">
      <body
        className={`${comfortaa.variable} font-comfortaa bg-background text-text antialiased`}
      >
        <AuthProvider>
          <div className="flex min-h-screen flex-col">
            {!isSocialsPage && <Navigation />}

            <main className="flex-1">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}